<?php

$json = json_encode(
	array(
		'Cities' => array(
			'Adelanto',
			'Agoura Hills',
			'Alameda',
			'Albany',
			'Alhambra',
			'Aliso Viejo',
			'American Canyon',
			'Anaheim',
			'Anderson',
			'Antioch',
			'Arcadia',
			'Arcata',
			'Arroyo Grande',
			'Artesia',
			'Arvin',
			'Atascadero',
			'Atwater',
			'Auburn',
			'Avenal',
			'Azusa',
			'Bakersfield',
			'Baldwin Park',
			'Banning',
			'Barstow',
			'Beaumont',
			'Bell',
			'Bell Gardens',
			'Bellflower',
			'Belmont',
			'Benicia',
			'Berkeley',
			'Beverly Hills',
			'Big Bear Lake',
			'Blythe',
			'Brawley',
			'Brea',
			'Brentwood',
			'Buena Park',
			'Burbank',
			'Burlingame',
			'Calabasas',
			'Calexico',
			'California City',
			'Calimesa',
			'Calipatria',
			'Calistoga',
			'Camarillo',
			'Campbell',
			'Canyon Lake',
			'Capitola',
			'Carlsbad',
			'Carpinteria',
			'Carson',
			'Cathedral City',
			'Ceres',
			'Cerritos',
			'Chico',
			'Chino',
			'Chino Hills',
			'Chowchilla',
			'Chula Vista',
			'Citrus Heights',
			'Claremont',
			'Clayton',
			'Clearlake',
			'Cloverdale',
			'Clovis',
			'Coachella',
			'Coalinga',
			'Colton',
			'Colusa',
			'Commerce',
			'Compton',
			'Concord',
			'Corcoran',
			'Corning',
			'Corona',
			'Coronado',
			'Costa Mesa',
			'Cotati',
			'Covina',
			'Crescent City',
			'Cudahy',
			'Culver City',
			'Cupertino',
			'Cypress',
			'Daly City',
			'Dana Point',
			'Davis',
			'Delano',
			'Desert Hot Springs',
			'Diamond Bar',
			'Dinuba',
			'Dixon',
			'Downey',
			'Duarte',
			'Dublin',
			'East Palo Alto',
			'El Cajon',
			'El Centro',
			'El Cerrito',
			'El Monte',
			'El Segundo',
			'Elk Grove',
			'Emeryville',
			'Encinitas',
			'Escalon',
			'Escondido',
			'Eureka',
			'Exeter',
			'Fairfield',
			'Farmersville',
			'Fillmore',
			'Firebaugh',
			'Folsom',
			'Fontana',
			'Fort Bragg',
			'Fortuna',
			'Foster City',
			'Fountain Valley',
			'Fowler',
			'Fremont',
			'Fresno',
			'Fullerton',
			'Galt',
			'Garden Grove',
			'Gardena',
			'Gilroy',
			'Glendale',
			'Glendora',
			'Goleta',
			'Gonzales',
			'Grand Terrace',
			'Grass Valley',
			'Greenfield',
			'Gridley',
			'Grover Beach',
			'Guadalupe',
			'Gustine',
			'Half Moon Bay',
			'Hanford',
			'Hawaiian Gardens',
			'Hawthorne',
			'Hayward',
			'Healdsburg',
			'Hemet',
			'Hercules',
			'Hermosa Beach',
			'Hesperia',
			'Highland',
			'Hollister',
			'Holtville',
			'Hughson',
			'Huntington Beach',
			'Huntington Park',
			'Huron',
			'Imperial',
			'Imperial Beach',
			'Indio',
			'Inglewood',
			'Ione',
			'Irvine',
			'Kerman',
			'King City',
			'Kingsburg',
			'La Canada Flintridge',
			'La Habra',
			'La Habra Heights',
			'La Mesa',
			'La Mirada',
			'La Palma',
			'La Puente',
			'La Quinta',
			'La Verne',
			'Lafayette',
			'Laguna Beach',
			'Laguna Hills',
			'Laguna Niguel',
			'Laguna Woods',
			'Lake Elsinore',
			'Lake Forest',
			'Lakewood',
			'Lancaster',
			'Lawndale',
			'Lemon Grove',
			'Lemoore',
			'Lincoln',
			'Lindsay',
			'Livermore',
			'Livingston',
			'Lodi',
			'Loma Linda',
			'Lomita',
			'Lompoc',
			'Long Beach',
			'Los Alamitos',
			'Los Altos',
			'Los Angeles',
			'Los Banos',
			'Lynwood',
			'Madera',
			'Malibu',
			'Manhattan Beach',
			'Manteca',
			'Marina',
			'Martinez',
			'Marysville',
			'Maywood',
			'McFarland',
			'Mendota',
			'Menifee',
			'Menlo Park',
			'Merced',
			'Mill Valley',
			'Millbrae',
			'Milpitas',
			'Mission Viejo',
			'Modesto',
			'Monrovia',
			'Montclair',
			'Montebello',
			'Monterey',
			'Monterey Park',
			'Moorpark',
			'Moreno Valley',
			'Morgan Hill',
			'Morro Bay',
			'Mountain View',
			'Murrieta',
			'Napa',
			'National City',
			'Newark',
			'Newman',
			'Newport Beach',
			'Norco',
			'Norwalk',
			'Novato',
			'Oakdale',
			'Oakland',
			'Oakley',
			'Oceanside',
			'Ojai',
			'Ontario',
			'Orange',
			'Orinda',
			'Orland',
			'Oroville',
			'Oxnard',
			'Pacific Grove',
			'Pacifica',
			'Palm Desert',
			'Palm Springs',
			'Palmdale',
			'Palo Alto',
			'Palos Verdes Estates',
			'Paramount',
			'Parlier',
			'Pasadena',
			'Patterson',
			'Perris',
			'Petaluma',
			'Pico Rivera',
			'Piedmont',
			'Pinole',
			'Pismo Beach',
			'Pittsburg',
			'Placentia',
			'Placerville',
			'Pleasant Hill',
			'Pleasanton',
			'Pomona',
			'Port Hueneme',
			'Porterville',
			'Poway',
			'Rancho Cordova',
			'Rancho Cucamonga',
			'Rancho Mirage',
			'Rancho Palos Verdes',
			'Red Bluff',
			'Redding',
			'Redlands',
			'Redondo Beach',
			'Redwood City',
			'Reedley',
			'Rialto',
			'Richmond',
			'Ridgecrest',
			'Rio Vista',
			'Ripon',
			'Riverbank',
			'Riverside',
			'Rocklin',
			'Rohnert Park',
			'Rolling Hills Estates',
			'Rosemead',
			'Roseville',
			'Sacramento',
			'Salinas',
			'San Bernardino',
			'San Bruno',
			'San Clemente',
			'San Diego',
			'San Dimas',
			'San Fernando',
			'San Francisco',
			'San Gabriel',
			'San Jacinto',
			'San Jose',
			'San Juan Capistrano',
			'San Leandro',
			'San Luis Obispo',
			'San Marcos',
			'San Marino',
			'San Mateo',
			'San Pablo',
			'San Rafael',
			'San Ramon',
			'Sanger',
			'Santa Ana',
			'Santa Barbara',
			'Santa Clara',
			'Santa Clarita',
			'Santa Cruz',
			'Santa Fe Springs',
			'Santa Maria',
			'Santa Monica',
			'Santa Paula',
			'Santa Rosa',
			'Santee',
			'Saratoga',
			'Sausalito',
			'Scotts Valley',
			'Seal Beach',
			'Seaside',
			'Sebastopol',
			'Selma',
			'Shafter',
			'Sierra Madre',
			'Signal Hill',
			'Simi Valley',
			'Solana Beach',
			'Soledad',
			'Solvang',
			'Sonoma',
			'South El Monte',
			'South Gate',
			'South Lake Tahoe',
			'South Pasadena',
			'South San Francisco',
			'St. Helena',
			'Stanton',
			'Stockton',
			'Suisun City',
			'Sunnyvale',
			'Susanville',
			'Taft',
			'Tehachapi',
			'Temecula',
			'Temple City',
			'Thousand Oaks',
			'Torrance',
			'Tracy',
			'Tulare',
			'Turlock',
			'Tustin',
			'Twentynine Palms',
			'Ukiah',
			'Union City',
			'Upland',
			'Vacaville',
			'Vallejo',
			'Victorville',
			'Villa Park',
			'Visalia',
			'Vista',
			'Walnut',
			'Walnut Creek',
			'Wasco',
			'Waterford',
			'Watsonville',
			'West Covina',
			'West Hollywood',
			'West Sacramento',
			'Westlake Village',
			'Westminster',
			'Whittier',
			'Wildomar',
			'Williams',
			'Willows',
			'Winters',
			'Woodlake',
			'Woodland',
			'Yorba Linda',
			'Yreka',
			'Yuba City',
			'Yucaipa'
		)
	)
);

$fp = @fopen('out.json','w');
fwrite($fp, $json);
fclose($fp);

?>











